### ISSUE TITLE
[Feature] 支持命令别名

### ISSUE THREAD

**Issue by MSDNicrosoft** [ArcletProject/nonebot-plugin-alconna#2]
## 请确认：

* [x] 新特性的目的明确
* [x] 我已经阅读了文档 [the wiki](https://arcletproject.github.io/docs/alconna/tutorial) 并且找不到类似特性

### 概要
`on_alconna` 支持命令的别名，就像 nonebot2 的 `on_command` 一样

注：这里的命令指的是根命令

我认为 `on_alconna` 要有 aliases 参数（可选）：

```python
from nonebot_plugin_alconna import on_alconna

matcher = on_alconna(
	Alconna(
    "一言"
	),
	aliases={"hitokoto"}
)

...

```

具体应有的效果就是，对于以下命令，`matcher` 都可以响应：
- `/一言`
- `/hitokoto`

**Comment by RF-Tar-Railt** [comment]
你现在可以进行如下选择以实现类似效果

1. 传入headers
```python
from nonebot_plugin_alconna import on_alconna

matcher = on_alconna(
	Alconna(
    ["/一言", "/hitokoto"]
	)
)
...
```
2. 主命令正则
```python
from nonebot_plugin_alconna import on_alconna

matcher = on_alconna(
	Alconna(
    ["/"],
    "(一言|hitokoto)"
	)
)
...
```
3. 使用快捷命令

```python
from nonebot_plugin_alconna import on_alconna

cmd = Alconna("/hitokoto")
cmd.shortcut("/一言", {"command": "/hitokoto"})
matcher = on_alconna(
	cmd
)
...
```

**Comment by MSDNicrosoft** [comment]
> 你现在可以进行如下选择以实现类似效果
> 
> 1. 传入headers
> 
> ```python
> from nonebot_plugin_alconna import on_alconna
> 
> matcher = on_alconna(
> 	Alconna(
>     ["/一言", "/hitokoto"]
> 	)
> )
> ...
> ```
> ...

第一种方法，当 `ALCONNA_USE_COMMAND_START=true` 时，如下代码没有效果：

```python
matcher = on_alconna(
    Alconna(
        ["一言", "hitokoto"]
    )
)
```

我的 `COMMAND_START` 是 `["!!"]`，
发送的消息是 `!!一言` 和 `!!hitokoto`

**Comment by RF-Tar-Railt** [comment]
> > 你现在可以进行如下选择以实现类似效果
> 
> > 
> 
> > 1. 传入headers
> 
> > 
> 
> > ```python
> 
> > from nonebot_plugin_alconna import on_alconna
> 
> > 
> 
> > matcher = on_alconna(
> 
> > 	Alconna(
> 
> >     ["/一言", "/hitokoto"]
> 
> > 	)
> 
> > )
> 
> > ...
> 
> > ```
> 
> > ...
> 
> 
> 
> 第一种方法，当 `ALCONNA_USE_COMMAND_START=true` 时，如下代码没有效果：
> 
> 
> 
> ```python
> 
> matcher = on_alconna(
> 
>     Alconna(
> 
>         ["一言", "hitokoto"]
> 
>     )
> 
> )
> 
> ```
> 
> 
> 
> 我的 `COMMAND_START` 是 `["!!"]`，
> 
> 发送的消息是 `!!一言` 和 `!!hitokoto`
> 
> 
> 
> 
那就使用第二种方式
命令传入的[...]与command_start是一类东西，alconna_use_command_start会把命令自己的headers替换掉

**Comment by MSDNicrosoft** [comment]
好的，我知道怎么做了。

**Comment by RF-Tar-Railt** [comment]
aliases也可以加

**Comment by MSDNicrosoft** [comment]
> aliases也可以加

~~那行吧~~
